config/routes.rb
Rails.application.routes.draw do

 root 'messages#index'
 devise_for :users


 resources :messages, :only => [:index, :new, :create, :show]
 
 resources :contacts do 
   resources :messages
 end

  resources :users, :only => [:show]  
 	
 end

app/models/contact.rb
class Contact < ActiveRecord::Base

belongs_to :user
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/message.rb
class Message < ActiveRecord::Base
 before_create :send_message

 belongs_to :user

 private
 #if create a message, the below is run
  def send_message
    begin  #meaning begin the code we want to run
      response = RestClient::Request.new(
        :method => :post,
        :url => "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
        :user => ENV['TWILIO_ACCOUNT_SID'],
        :password => ENV['TWILIO_AUTH_TOKEN'],
        :payload => { :Body => body,
                      :To => to,
                      :From => from }
      ).execute
    rescue RestClient::BadRequest => error #if there is an exception, then return false, which stops the save in active record
      message = JSON.parse(error.response)['message'] #this parses the error message, converting to a hash, and pulling out the message key of the hash
      errors.add(:base, message) #adds errors to the active record object. ":base" refers to the entire object. IF we wanted to specify something wrong with body, we would replace with ":body"
      false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable, :rememberable 

 has_many :contacts

 has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   #def current_user
    #@current_user ||= User.find(session[:user_id]) if session[:user_id]
 # end
  
  helper_method :current_user

  def authorize
    redirect_to login_path, alert: "Not authorized" if current_user.nil? #relates to before filters. If user not logged in (ie, current_user = nil), then send error message if takes action not authorized to take
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :authenticate_user!
 
  def index 
    @contacts = Contact.all
    @user = current_user
    #if params[:query]
     # @searched_contacts = Contact.basic_search(params[:query])
    #end
  end

  def new 
    @contact = current_user.contacts.new
  end

  def create
    @contacts = Contact.all
    @contact = current_user.contacts.new(contact_params)
    if @contact.save
        flash[:notice] = "Contact created."
        redirect_to contacts_path
      else
        render 'new' 
      end
  end

=begin
  def edit  
    if User.find(params[:user_id]) != current_user
      flash[:notice] = "You are not permitted to edit this contact"
      redirect_to root_path
    else
      @user = current_user
      @contact = Contact.find(params[:id])
    end
  end

  def update 
    @contact = Contact.find(params[:id])
    @contacts = contact.contacts
    

    @contact.update(contact_params)
     flash[:notice] = "Contact Updated"
    redirect_to root_path
  end

 def destroy 
    @contact = Contact.find(params[:id])
    @contact.destroy
     flash[:notice] = "Contact Deleted"
    redirect_to root_path
 end
=end
 
 private

    def contact_params
      params.require(:contact).permit(:name, :number)
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]  #devise method: without being logged in, can only see the index and show
  
  def index 
    @messages = Message.all  
  end

  def new 
    @message = current_user.messages.build
    @user = current_user #add number to user field(? or does twilio require only specified numbers)
    if Contact.where(:id => params[:contact_id]).first 
      @contact = Contact.find(params[:contact_id])
    end
  end

  def create
    phones = message_params[:to]
    phones.each do |phone|
      contact = Contact.find_by(phone: phone)
      @message = current_user.messages.build(message_params)
      @message.to = phone 
      @message.save
    end
     if @message.errors.any?
      render 'new'
    else
      flash[:notice] = "Message sent!"
      redirect_to messages_path
    end
  end

=begin
  def show
    @message = Message.find(params[:id]) 
    render('messages/show.html.erb')
  end

  def edit 
    @message = Message.find(params[:id])
  end

  def update 
    @message = Message.find(params[:id])
    if @message.update(message_params)
     flash[:notice] = "Message updated."
      redirect_to message_path(@message)
    else
      render 'edit'
    end
  end

 def destroy 
    @message = Message.find(params[:id])
    @message.destroy
     flash[:notice] = "message Deleted"
    redirect_to messages_path
 end
=end

 private

    def message_params
      params.require(:message).permit(:to, :from, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 before_filter :authenticate_user!

  def show
	@user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<%= form_for (@contact) do |f| %>
  <div class="form-group">
    <%= f.label :name %></br> 
    <%= f.text_field :name%>
  </div>
  
   <div class="form-group">
    <%= f.label :number %></br>
    <%= f.text_field :number %>
  </div>

  <%= f.hidden_field :user_id, :value => current_user.id %>
  
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

<%= link_to "Home Page", root_path, :class => "btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div id="user_nav">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>  
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> |
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/messages/_new_message_contact.html.erb
<% if @message.errors.any? %>
	<p> Something went wrong: </p>
	<ul>
	<% @message.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

</br>
<h4> New Message to <%= @contact.name %>: </h4>
</br>
<%= form_for [@contact, @message] do |f| %>
	<%= f.label :to %>
	<%= f.text_field :to, value: @contact.number %>
	<%= f.label :from %>
	<%= f.text_field :from %>
	<%= f.label :body %>
	<%= f.text_field :body %>
	<%= f.submit %>
<% end %>
</br>

app/views/messages/_new_message_nocontact.html.erb
<% if @message.errors.any? %>
	<p> Something went wrong: </p>
	<ul>
	<% @message.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @message do |f| %>
	<%= f.label "Select Contact(s) to Send Message to:" %></br>
    <%= f.collection_check_boxes(:to, current_user.contacts, :number, :name, multiple: true) %></br>
	<%= f.label :from %>
	<%= f.text_field :from %>
	<%= f.label :body %>
	<%= f.text_field :body %>
	<%= f.submit %>
<% end %>

<h3> Add Contacts for this message </h3>

<%= link_to "Add Contacts For this Message", new_message_path, :class => "btn btn-default", id: "new_contact", remote: true  %>

</br>

app/views/messages/index.html.erb
<h1>Messages</h1>

<ul>
 <%@messages.each do |message| %>
   <li><%= link_to message.id, message_path(message) %></li>
 <% end %>
</ul>

</br>
</br>
<% if current_user %>
  <%= link_to "Profile", user_path(current_user) %> </br> </br>

  <%= link_to "New Message", new_message_path %> </br> </br>


  <%= link_to "View Your Address Book", contacts_path %></br>
<% end %>

 

app/views/messages/new.html.erb
<h1>New Message</h1>

<% if @contact %>
	<%= render 'new_message_contact' %>
<% else %>
	<%= render 'new_message_nocontact' %>
<% end %>

<%= link_to "Home Page", root_path, :class => "btn btn-default" %>

app/views/users/show.html.erb
<%= content_for(:title, "Profile") %>

<h2> <%= @user.email %>: Here is your profile </h2></br>

<h4> Email: <%= @user.email %> </h4></br>

<%= link_to "View Contacts", contacts_path, :class => "btn btn-default" %>

</br></br>


</br>

<%= link_to "Home Page", root_path, :class => "btn btn-default" %>